---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ALL-READ-POD
rules:
- apiGroups: [ '' ]
  resources: [ 'pods' ]
  verbs: [ 'get', 'list', 'watch' ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ALL-Prometheus-READ-POD
  namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ALL-READ-POD
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:prometheus
  namespace: prometheus
