---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: ''
  kind: ServiceAccount
  name: bob
  namespace: default # The ClusterRoleBinding "admin-bob" is invalid: subjects[0].namespace: Required value
